theme: jekyll-theme-minimal
title: Camryn's Portfolio
#About Me(Camryn Martine)
##Fun Facts
-I am a middle child
-I am 20
-I am a second year GIMM student

##Hobbies
-Video Games
-Reading
-Listening to music
-Baking

